version: '3'

services:
  rest-server:
    container_name: rest-server
    depends_on:
      - database
    build:
      context: ./
      target: rest-server-image
    command: /usr/local/bin/rest-server
    restart: always
    ports: "8080:8080"

  database:
    container_name: pgdb
    image: postgres:15.1
    restart: always
    ports: "5432:5432"
    volumes:
      ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-secret
